# Generated by Django 4.1.7 on 2023-04-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('address', models.CharField(db_column='address', max_length=256)),
                ('kids', models.CharField(db_column='kids', max_length=256)),
                ('bio', models.CharField(db_column='bio', max_length=256)),
                ('birth_year', models.IntegerField(db_column='birth_year')),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', default='1900-01-01')),
                ('salary', models.IntegerField(blank=0, null=True)),
                ('note', models.CharField(db_column='note', max_length=256)),
                ('has_happened', models.BooleanField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popins_app.parent')),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(db_column='review')),
                ('review_date', models.DateField(db_column='date', default='1900-01-01')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent_reviews', to='popins_app.review'),
        ),
        migrations.AddField(
            model_name='parent',
            name='sessions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parent_sessions', to='popins_app.session'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Nanny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('address', models.CharField(db_column='address', max_length=256)),
                ('bio', models.CharField(db_column='bio', max_length=256)),
                ('links', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('birth_year', models.IntegerField(db_column='birth_year')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nanny_reviews', to='popins_app.review')),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nanny_sessions', to='popins_app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': "nanny's",
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(db_column='note', max_length=256)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='popins_app.nanny')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='popins_app.session')),
            ],
            options={
                'db_table': 'interests',
            },
        ),
    ]
