# Generated by Django 4.1.7 on 2023-04-08 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popins_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(db_column='is_parent', default=False)),
                ('is_nanny', models.BooleanField(db_column='is_nanny', default=False)),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('bio', models.TextField(db_column='bio', max_length=256)),
                ('birth_year', models.IntegerField(db_column='birth_year')),
                ('address', models.CharField(db_column='address', max_length=256)),
                ('link', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('User_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_column='date')),
                ('salary', models.IntegerField(db_column='salary', default=50)),
                ('note', models.TextField(db_column='note', max_length=256)),
                ('has_happened', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='popins_app.profile')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(db_column='review')),
                ('review_date', models.DateField(auto_now_add=True, db_column='date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='popins_app.profile')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(db_column='note', max_length=256)),
                ('talked', models.BooleanField()),
                ('status', models.BooleanField()),
                ('session', models.ManyToManyField(db_table='Session_Interest', to='popins_app.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='popins_app.profile')),
            ],
            options={
                'db_table': 'interest',
            },
        ),
    ]
