# Generated by Django 4.1.7 on 2023-04-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popins_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='session',
            table='sessions',
        ),
    ]
