# Generated by Django 4.1.7 on 2023-04-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popins_app', '0003_rename_user_id_profile_user_remove_interest_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='session',
            table='sessions',
        ),
    ]
