# Generated by Django 4.1.7 on 2023-04-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popins_app', '0004_alter_session_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='nanny',
            new_name='user',
        ),
    ]
