# Generated by Django 4.1.7 on 2023-04-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popins_app', '0005_rename_nanny_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='interested_nannys',
            new_name='interested_nannies',
        ),
    ]
