# Generated by Django 4.1.7 on 2023-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popins_app', '0008_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_nanny',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, db_column='address', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, db_column='bio', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.IntegerField(db_column='birth_year', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_parent',
            field=models.BooleanField(db_column='is_parent'),
        ),
    ]
