# Generated by Django 4.1.5 on 2023-05-24 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('popins_app', '0009_remove_profile_is_nanny_remove_profile_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(db_column='date', default=django.utils.timezone.now),
        ),
    ]
